
server:
  port: 9090
spring:
  application:
    name: uygunbilet-gateway
  cloud:
    gateway:
      routes:
        - id: uygunbilet-service
          uri: lb://uygunbilet-service
          predicates:
            - Path=/users/**,/seats/**,/tickets/**,/trips/**
        - id: emlakcepte-payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/payments/**
    